### ISSUE TITLE
does not work with OpenClassrooms Tutorial example

### ISSUE THREAD

**Issue by ligne13** [bestmomo/scafold#10]
Hi,
It seems that there is an issue with your OpenClassrooms Laravel Tutorial and this Scafold (chapitre L'AUTHENTIFICATION).
I can't login in the demo app because the method used to check the password always returns false. In the tutorial, passwords are encrypted with the PHP bcrypt function, but they are checked by default by the Illuminate\Hashing\BcryptHasher with the PHP password_hash function : 
[30] $hash = password_hash($value, PASSWORD_BCRYPT, ['cost' => $cost]);

The PHP password_check function in the BCryptHasher->check method returns false :
[53] return password_verify($value, $hashedValue);

And so it is impossible to login... Shouldn't it be better to use the BCryptHasher->make method to store the passwords when registering in the demo app ?

PS : sorry I know this is not the right place to post this message, but I can't find another way to reach you. Great tutorial otherwise ;-)

**Comment by bestmomo** [comment]
Hi,

_bcrypt_ is a Laravel helper with this code :

```
function bcrypt($value, $options = [])
{
    return app('hash')->make($value, $options);
}
```

So it uses the hasher and should work.

But take care that in my tutorial in the previous lesson (Les ressources 2/2) I use `setPasswordAttribute` scope to crypt the password. Maybe you crypt it twice.

**Comment by ligne13** [comment]
Oh of course !!! thank you !

I forgot this line...
