### ISSUE TITLE
request to fix the readme.md

### ISSUE THREAD

**Issue by hi-time** [bestmomo/scafold#11]
hi bestmomo developers,

the other day,  i noticed the bellow reading the readme.md.
- current
  
  <pre>Bestmomo\Scafold\ScafoldServiceProvider::class,</pre>
- fixed
  
  <pre>Bestmomo\Scafold\ScafoldServiceProvider,</pre>

how do you think ?

best regards
hi-time.

**Comment by bestmomo** [comment]
Hi,

The current is the new PHP syntax, but twice are good.
