### ISSUE TITLE
Fails If Namespace Is Already Set

### ISSUE THREAD

**Issue by mikebronner** [bestmomo/scafold#2]
If I already set up the app namespace for my project, installation of this package fails with the following error when trying to run artisan commands:

```
[ReflectionException]                                          
  Class App\Http\Controllers\Auth\AuthController does not exist
```

**Comment by bestmomo** [comment]
Good catch. Corrected in [this commit](https://github.com/bestmomo/scafold/commit/c429842c41189a2e698b0ed00c2293d361ec6c73).

Thanks.
