### ISSUE TITLE
overwriting existing views

### ISSUE THREAD

**Issue by ghost** [bestmomo/scafold#3]
Hi, thanks for this great package. I firstly followed the instructions on laravel 5.1 authentication docs.As told in there, I created the two views by using the sample login and register forms. 

resources/views/auth/login.blade.php
resources/views/auth/register.blade.php

Since these look like crap, I googled and found your scaffold and followed the instructions. However artisan vendor:publish did not overwrite the existing files which I created above. I removed those and published again and it worked fine. 

It'd be great if you enable overwriting of any existing files on vendor:publish.

Thanks.

**Comment by bestmomo** [comment]
Hello

You can use --force option on vendor:publish command to overwrite existing files.

**Comment by ghost** [comment]
Oops, sorry i'm new to artisan, thanks for informing.
