### ISSUE TITLE
Class not found on clean install via composer

### ISSUE THREAD

**Issue by novalis111** [bestmomo/scafold#5]
Hi, after a clean install (on a fresh project) like in the README a subsequent call "composer update" fails with the following error. The only additional service provider installed is barryvdh/laravel-ide-helper, apart from that it's a vanilla Laravel 5.1. Any clue? I'm fairly new to Laravel, so my search ended when digging into the Autoloader and its magic...

```
vagrant@dev:/var/www/example.com/web$ php artisan clear-compiled
PHP Fatal error:  Class 'Bestmomo\Scafold\ScafoldServiceProvider' not found in /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
PHP Stack trace:
PHP   1. {main}() /var/www/example.com/web/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/example.com/web/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:98
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:206
PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
PHP   7. Illuminate\Foundation\ProviderRepository->load() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:507
PHP   8. Illuminate\Foundation\ProviderRepository->compileManifest() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:60
PHP   9. Illuminate\Foundation\ProviderRepository->createProvider() /var/www/example.com/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:114



  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Bestmomo\Scafold\ScafoldServiceProvider' not found
```

**Comment by bestmomo** [comment]
Hello,
Did you add Bestmomo\Scafold\ScafoldServiceProvider::class in config/app.php before composer update ?

**Comment by novalis111** [comment]
> Did you add Bestmomo\Scafold\ScafoldServiceProvider::class in
> config/app.php before composer update ?

Did that, i followed all README directives. When i remove it from
config/app.php "composer update && php artisan clear-compiled" succeeds,
after re-adding it, it fails with the mentioned error.

**Comment by bestmomo** [comment]
Hi, it's weird because barryvdh/laravel-ide-helper just add a file in root. Try to make a **composer dumpautoload** to regenerate autoload.

**Comment by novalis111** [comment]
> Hi, it's weird because barryvdh/laravel-ide-helper just add a file in
> root. Try to make a _composer dumpautoload_ to régénerate autoload.

Thanks for your help! No luck with that... I have a script in
composer.json which recompiles the ide-helper stuff, so i think it's not
composer which fails but artisan on "php artisan clear-compiled"

**Comment by bestmomo** [comment]
You also can use the [generated version](https://gist.github.com/barryvdh/5227822) of ide helper.

**Comment by novalis111** [comment]
> You also can use the generated version
> https://gist.github.com/barryvdh/5227822 of ide helper.

I could, but even without the ide-helper in config/app.php the artisan
command fails. It is indeed weird, as you are following all conventions
for the Autoloader to find and load your ServiceProvider Class... I
couldn't spot a difference/typo/whatever with other Server Provider
Classes either.

**Comment by novalis111** [comment]
Oh well... 

```
mv ScafoldServiceprovider.php ScafoldServiceProvider.php
```

I won't issue a pull request for that, but you should change it ;) Thanks for your help and your work, all is fine now.

**Comment by bestmomo** [comment]
Good catch ! As I use Windows I dont detect it ! Corrected on [this commit](https://github.com/bestmomo/scafold/commit/681cf9b6a398359d8c6eeea900e1c9d9a293c914).
