### ISSUE TITLE
l'adresse email n'existe pas

### ISSUE THREAD

**Issue by Nikolas33** [bestmomo/scafold#6]
Bonsoir Maurice,

Déjà un grand merci pour vos tutos que je suis à la lettre sur openclassrooms, cela m'aide énormément et vous êtes très pédagogue.
Je débute avec Laravel et suite à la l'étape d'authentification je me butte pas un pb pour lequel je ne sais pas par ou investiguer.

Lorsque je m'authentifie j'obtiens toujours le message d'erreur l'adresse email n'existe pas.
Par contre dès lors que je reset mon mdp je suis bien redirigé sur la page home en me disant que je suis loggué. 

Avez vous des pistes pour m'aider à avancer car j'avoue que je me sens un peu perdu là :-)
Merci encore d'avance, Nicolas

**Comment by bestmomo** [comment]
Bonsoir Nicolas,
C'est curieux de recevoir un message de ce genre à l'authentification étant donné que la vérification est globale avec à la fois l'email et le mot de passe avec par défaut le message "These credentials do not match our records.".

**Comment by Nikolas33** [comment]
Je suis reparti d'un projet vierge en ajoutant les classes requises puis cette classe et tout fonctionne, je vais pas chercher plus loin, le principal c'est que ça fonctionne désormais :)
