### ISSUE TITLE
OpenClassRoom

### ISSUE THREAD

**Issue by FHoulbreque** [bestmomo/scafold#7]
Hello,

Following your Laravel 5.1 tutorial, you ask people to get your package from GitHub.

I can see you recently removed Glyphicons and the included CSS. Your tutorial isn't yet updated for these changes so... have you replaced all this by CDN links ? Can I still follow your tutorial without any issue ?

Kind regards.

**Comment by bestmomo** [comment]
Hello,

My tutorial on OpenClassRoom will be soon updated.

[This one has been updated](http://laravel.sillo.org/creer-un-package/).

I use CDN, I think it's better.

Regards.
