### ISSUE TITLE
Changing Scaffold Authentication Default Files

### ISSUE THREAD

**Issue by DaltonCastro** [bestmomo/scafold#8]
Hy guys,

Would be a problem if I change the default Auth files according with my bussiness rules?
Will Laravel replace my changes when I perfom 'composer update'?

By example: Changing the default User.php model (located originally at app/).

Thanks.

**Comment by bestmomo** [comment]
Hi,

The default user model is defined in **config/auth.php** :

```
'model' => App\User::class,
```

So you must change the namespace there.

**Comment by DaltonCastro** [comment]
Hi,

I did this, it's working....But my doubt is if composer update cmd overrides all my changes when I execute it.

Thanks.

**Comment by bestmomo** [comment]
Composer makes changes only in vendor folder to update libraries and autoload.

**Comment by DaltonCastro** [comment]
Good to know!

Thanks for your help.
