### ISSUE TITLE
HomeController with namespace different of App

### ISSUE THREAD

**Issue by argentinaluiz** [bestmomo/scafold#9]
When use command for change namespace application, the HomeController don't work because namespace beginning with App.

**Comment by bestmomo** [comment]
Hum, it's annoying because dynamic class extension is not possible... I wonder how to solve this...

**Comment by argentinaluiz** [comment]
Perhaps move the app classes to app folder, so you can change the namespace

**Comment by bestmomo** [comment]
I've solved it. I have created an alias in [this commit](https://github.com/bestmomo/scafold/commit/3a5f9eabf86ff14d6488f42df27570b6952af0ad) with [this little correction](https://github.com/bestmomo/scafold/commit/ce8fe0cb84c14ae28cf724fff28e42bf6a042391).

**Comment by argentinaluiz** [comment]
Thanks! 
;)
